name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ !contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) }}
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "We do not accept PRs. If you are a customer, please contact us via our website."
